name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Compiler le projet
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - name: Tester la fonction add
        run: |
          cd build
          ./calculator add 10 5
